### ISSUE TITLE
CSS: Spaces in sums are not preserved

### ISSUE THREAD

**Issue by ollieabbey** [primefaces-extensions/resources-optimizer-maven-plugin#243]
According to the [documention](https://developer.mozilla.org/en-US/docs/Web/CSS/calc-sum#description) for `calc-sum`, the whitespace around a `+` or `-` in a calculation must be preserved. The CssCompressor currently doesn't respect this outside of `calc` functions.

E.g. 

```css
.example {
    width: clamp(2.5rem, 1.6667rem + 4.1667vw, 5rem);
    height: max(1rem + 5px, 2rem - 8px);
}
```

Is compressed to 

```css
.example{width:clamp(2.5rem,1.6667rem+4.1667vw,5rem);height:max(1rem+5px,2rem - 8px)}
```

i.e. losing the whitespace that should be preserved.

`calc` expressions are preserved by [this line](https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/blob/master/src/main/java/org/primefaces/extensions/optimizerplugin/optimizer/CssCompressor.java#L149).

<br>

A simple fix could be to remove the plus sign from the regexps on lines [250](https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/blob/master/src/main/java/org/primefaces/extensions/optimizerplugin/optimizer/CssCompressor.java#L250) and [343](https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/blob/master/src/main/java/org/primefaces/extensions/optimizerplugin/optimizer/CssCompressor.java#L343) in the CssCompressor, but this would lose the benefit of compressing expressions like

```css
.first + .second { height: 10 px; }
```

to 

```css
.first+.second{height:10px}
```
