### ISSUE TITLE
CSS Compressor: Incorrect optimization for transition property

### ISSUE THREAD

**Issue by miroskow** [primefaces-extensions/resources-optimizer-maven-plugin#72]
Used resources-optimizer-maven-plugin v2.3.8

Before optimization:

```css
.transition-test {
	transition: all 0s ease 0s;
	transition-delay: 0s;
	transition-duration: 0s;
	transition-delay: 0ms;
	transition-duration: 0ms;
}
```

After optimization:

```css
.transition-test{transition:all 0 ease 0;transition-delay:0;transition-duration:0;transition-delay:0;transition-duration:0}
```

Removing the units of measure s, ms for a value of 0 is invalid for the transition property.

https://developer.mozilla.org/en-US/docs/Web/CSS/time
"0 Although unitless zero is allowed for [length's], it's invalid for [time's]."

**Comment by melloware** [comment]
OK here looks like the original issue from the YUI Compressor: https://github.com/yui/yuicompressor/issues/256

Can you try my suggestion in that ticket just for now...

```css
.transition-test {
	transition: all 0.0s ease 0.0s;
	transition-delay: 0.0s;
	transition-duration: 0.0s;
	transition-delay: 0.0ms;
	transition-duration: 0.0ms;
}
```
