### ISSUE TITLE
CSS Compressor:  Invalid whitespace removal / @supports () "or" () 

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/resources-optimizer-maven-plugin#76]
original Issue: https://github.com/yui/yuicompressor/issues/340

Raw:

```css
.foo {
    @supports (backdrop-filter: blur(10px)) or (-webkit-backdrop-filter: blur(10px)) {
        background: rgba(69, 69, 69, 0.5);
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
      }
}
```

Incorrectly compressed to:

```css
.foo {
    @supports (backdrop-filter: blur(10px)) or(-webkit-backdrop-filter: blur(10px)) {
        background: rgba(69, 69, 69, 0.5);
        backdrop-filter: blur(10px);
        -webkit-backdrop-filter: blur(10px);
      }
}
```

No space after the `or` causes issues in Chrome
