### ISSUE TITLE
CSS Compressor: Space before : are removed inside media query

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/resources-optimizer-maven-plugin#77]
Original Issue: https://github.com/yui/yuicompressor/issues/334

```css
@media screen and (-ms-high-contrast: none) {
    body :focus {
      outline: 2px solid #5e9ed6;
    }
}
```
The space before : is removed and changing the selector.

```css
@media screen and (-ms-high-contrast: none) {
    body:focus {
      outline: 2px solid #5e9ed6;
    }
}
```

The space before : should not be removed.
