### ISSUE TITLE
CSS Compressor: Text-Shadow CSS after "compression"

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/resources-optimizer-maven-plugin#78]
Original Issue: https://github.com/yui/yuicompressor/issues/91

```css
.test2 {
  -webkit-box-shadow: 0 0;
  -moz-box-shadow: 0 0;
  box-shadow: 0 0;
  text-shadow: 0 0;
}
```

After compression incorrectly makes it `0`.
```css
.test2 {
  -webkit-box-shadow: 0;
  -moz-box-shadow: 0;
  box-shadow: 0;
  text-shadow: 0;
}
```
